### ISSUE TITLE
Message signing error

### ISSUE THREAD

**Issue by fuzious** [dialectlabs/blinks#30]
Hi everyone, I am facing a weird error 
When using dial.to test my blink https://blinks.skatechain.org/

It is working fine and all but when on X i get a weird error transaction data missing that also only some setups like on one of my setup it is working fine but on one of it isnt

https://dial.to/developer?url=https%3A%2F%2Fblinks.skatechain.org%2Fapi%2Factions%2Fmint&cluster=mainnet

I just need a message to be signed and no transactions to be sent.
as per blinks.xyz it shows me an error, i think it expects a transaction object , but I dont need a tx to be done i just need a message to be signed , can someone please help me with it thanks

Update:
I put the messaged to be signed in the transaction object 
But now... on testing on some PCs phantom wallet does not even pop up to sign the message but on some it pops up to sign the message and works well
for backpack the screen is all grey and doesn't work at all

![image](https://github.com/user-attachments/assets/0705ee59-92f0-4e6b-a53b-4ae83365c04e)

**Comment by fsher** [comment]
@fuzious Hey there!

Since sign message was only recently released, wallets and clients need some time to update and release their extensions for sign message to work on X.

In order to avoid error behavior it's possible to pass a header in your GET response to indicate to the client that this blink has certain features that work from actions spec version x.x.x. Please see: https://docs.dialect.to/documentation/actions/specification/versioning-and-multichain-compatibility

**Comment by 0xfzs** [comment]
@fsher but I don't think versioning is the issue since on one of my PC with phantom+dialect it works but on another PC it doesn't with the same extensions and browser.

Also what about the greying error of backpack

**Comment by fsher** [comment]
@0xfzs Hey! By "it works" you mean on X or on dial.to?

**Comment by fuzious** [comment]
It works on X, you can try for yourself if you want https://x.com/CoinMaamaa/status/1844773016665805206
Attaching the screenshots and the message is indeed signed on one of my PCs but on other it doesn't


![Screenshot from 2024-10-14 21-02-13](https://github.com/user-attachments/assets/53d16892-a6a6-4dd7-8bd9-63d0c415e695)

**Comment by fuzious** [comment]
@fsher For setups that it is not working for them even phantom wallet doesn't pop up. It just goes into executing and then goes back to the landing page.
I have already tried these:
- Turned off blinks on X on backpack (because i dont think they have it supported yet, couldn't mint by backpack on any of my PCs)
- Selected phantom on dialect chrome extension on all my PCs
- Still on some PCs the wallet does pop up and on some it doesn't 

Also on the code side of things
- I added a `transaction` field in the signing request, I dont think it was required but just to pass the blink inspector I added that field but still the results were same on some PCs it worked on some it didn't

**Comment by fsher** [comment]
@fuzious could you also send the version of the dialect extension you have installed?

**Comment by fuzious** [comment]
Hi @fsher getting this issue with Phantom version as `24.21.0` and dialect version `0.5.0` 
![image](https://github.com/user-attachments/assets/f9768323-b8b9-4afd-afea-2207fd08fd42)

**Comment by fuzious** [comment]
OK, it worked after I disabled native blinks on phantom.
Thanks @fsher
