### ISSUE TITLE
useAction missing ability to pass `ActionProvider` 

### ISSUE THREAD

**Issue by ngundotra** [dialectlabs/blinks#38]
This was causing us issue in react-native app

https://github.com/dialectlabs/blinks/blob/cadc210e016ff2e252079176db1f6becbcbdc815/packages/blinks-core/src/hooks/useAction.ts#L63

**Comment by zhelezkov** [comment]
thanks for report. we're working rn to update `blinks-react-native` package to latest version of `blinks-core` which introduced some changes in the API especially how adapter should be passed. we'll update issue when it's done
